### PR TITLE
Added new api call and edities

### PR DESCRIPTION
**Pull request by karabayyazilim**
Manager announcement api call added

New helper method added `userInfo()`

`package:create` command new feature `make:test` added

### CODE REVIEW

**Comment by ahmetarsiv** [comment]
@karabayyazilim Is it correct to give company_id nullable in request? because data will be retrieved according to company id

**Comment by ahmetarsiv** [comment]
@karabayyazilim Request validations are not specified as **numeric** in the company_id line!

**Comment by karabayyazilim** [comment]
@ahmetarsiv  The value there is not important to me because whatever comes up I add my own company_id

` $request->merge(['company_id' => Helper::userInfo()->company_id]);`

**Review by ahmetarsiv — APPROVED** [review]
Completed

**Pull request merged**
